# Generated by Django 2.0.3 on 2018-03-17 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StatPer120Minutes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_date', models.DateTimeField()),
                ('name', models.CharField(max_length=100)),
                ('relation_id', models.IntegerField()),
                ('additional_field', models.IntegerField()),
            ],
            options={
                'db_table': 'stat_per_120_minutes',
            },
        ),
        migrations.CreateModel(
            name='StatPer1440Minutes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_date', models.DateTimeField()),
                ('name', models.CharField(max_length=100)),
                ('relation_id', models.IntegerField()),
                ('additional_field', models.IntegerField()),
            ],
            options={
                'db_table': 'stat_per_1440_minutes',
            },
        ),
        migrations.CreateModel(
            name='StatPer20Minutes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_date', models.DateTimeField()),
                ('name', models.CharField(max_length=100)),
                ('relation_id', models.IntegerField()),
                ('additional_field', models.IntegerField()),
            ],
            options={
                'db_table': 'stat_per_20_minutes',
            },
        ),
        migrations.CreateModel(
            name='StatPer360Minutes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_date', models.DateTimeField()),
                ('name', models.CharField(max_length=100)),
                ('relation_id', models.IntegerField()),
                ('additional_field', models.IntegerField()),
            ],
            options={
                'db_table': 'stat_per_360_minutes',
            },
        ),
        migrations.CreateModel(
            name='StatPer60Minutes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_date', models.DateTimeField()),
                ('name', models.CharField(max_length=100)),
                ('relation_id', models.IntegerField()),
                ('additional_field', models.IntegerField()),
            ],
            options={
                'db_table': 'stat_per_60_minutes',
            },
        ),
        migrations.CreateModel(
            name='StatPerMinute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_date', models.DateTimeField()),
                ('name', models.CharField(max_length=100)),
                ('relation_id', models.IntegerField()),
                ('additional_field', models.IntegerField()),
            ],
            options={
                'db_table': 'stat_per_minute',
            },
        ),
    ]
