# Generated by Django 2.0.3 on 2018-03-17 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamo', '0002_statper3600minutes'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatPer7600Minutes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_date', models.DateTimeField()),
                ('name', models.CharField(max_length=100)),
                ('relation_id', models.IntegerField()),
                ('additional_field', models.IntegerField()),
            ],
            options={
                'db_table': 'stat_per_7600_minutes',
            },
        ),
    ]
